site_name: Conventional Message

theme:
    name: "material"

plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: false
                    show_root_toc_entry: false

nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - How-To Guides: howto.md
    - Reference: reference.md
    - Explanation: explanation.md
